# Generated by Django 6.0.5 on 2026-05-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_enabled', models.BooleanField(default=True, help_text='When False, all /api/ endpoints return 503 Maintenance Mode.')),
                ('maintenance_message', models.CharField(default='The API is currently undergoing maintenance. Please try again later.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Configuration',
            },
        ),
    ]
